'''
Utilities for patch clamp loading and analysis from labview/axon setup
'''
import pandas as pd

def extract_data_and_metadata(csv_file_path):

    """
    Take a csv file generated by labview and parse it into data, and
    metadata.
    """
    data = pd.read_csv(csv_file_path, skiprows=5)

    metadata = pd.read_csv(csv_file_path, sep=':', header=None, nrows=3, index_col=False)
    metadata.index = ['resolution', 'num_points', 'date']
    metadata.columns = ['original_title', 'value']
    metadata = metadata.T

    return data, metadata